restaurantcollector/main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name ='home'),
    path('about/', views.about, name='about'),
    path('restaurants/', views.restaurants_index, name='index'),
    path('restaurants/<int:restaurant_id>/', views.restaurants_detail, name="detail"),
    path('restaurants/create/', views.RestaurantCreate.as_view(), name='restaurants_create'),
    path('restaurants/<int:pk>/update/', views.RestaurantUpdate.as_view(), name='restaurants_update'),
    path('restaurants/<int:pk>/delete/', views.RestaurantDelete.as_view(), name='restaurants_delete'),
    path('restaurants/<int:restaurant_id>/add_reservation/', views.add_reservation, name='add_reservation'),
    path('restaurants/<int:restaurant_id>/delete_reservation/<int:reservation_id>/', views.delete_reservation, name='delete_reservation'),
    path('restaurants/<int:restaurant_id>/assoc_dish/<int:dish_id>/', views.assoc_dish, name='assoc_dish'),
    path('dishes/', views.DishList.as_view(), name='dishes_index'),
    path('dishes/<int:pk>/', views.DishDetail.as_view(), name='dishes_detail'),
    path('dishes/create/', views.DishCreate.as_view(), name='dishes_create'),
    path('dishes/<int:pk>/update/', views.DishUpdate.as_view(), name='dishes_update'),
    path('dishes/<int:pk>/delete/', views.DishDelete.as_view(), name='dishes_delete'),
    path('accounts/signup/', views.signup, name='signup'),
]

restaurantcollector/restaurantcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

restaurantcollector/main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

# Create your models here.

SEATS = (
    ('I', 'Inside'),
    ('P', 'Patio')
)

class Dish(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('dishes_detail', kwargs={'pk': self.id})

class Restaurant(models.Model):
    name = models.CharField(max_length=100)
    cuisine = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    city = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    stars = models.IntegerField()
    dishes = models.ManyToManyField(Dish)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('detail', kwargs={'restaurant_id': self.id})

class Reservation(models.Model):
    date = models.DateField('Reservation Date')
    time = models.TimeField(auto_now=False, auto_now_add=False)
    seating = models.CharField(
        max_length=1,
        choices=SEATS,
        default=SEATS[0][0]   
    )
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.get_seating_display()} on {self.date}"
    class Meta:
        ordering = ['-date']

restaurantcollector/main_app/forms.py
from django.forms import ModelForm
from .models import Reservation

class ReservationForm(ModelForm):
  class Meta:
    model = Reservation
    fields = ['date', 'time', 'seating']

restaurantcollector/main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Reservation, Restaurant, Dish
from .forms import ReservationForm
from datetime import date, time, datetime
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

def home(request):
    return render(request, 'home.html')
def about(request):
  return render(request, 'about.html')

@login_required
def restaurants_index(request):
  restaurants = Restaurant.objects.filter(user=request.user)
  return render(request, 'restaurants/index.html', { 'restaurants': restaurants })

@login_required
def restaurants_detail(request, restaurant_id):
  restaurant = Restaurant.objects.get(id=restaurant_id)
  # Get the dishes the restaurant doesn't have
  dishes_restaurant_doesnt_have = Dish.objects.exclude(id__in = restaurant.dishes.all().values_list('id'))
  reservation_form = ReservationForm()
  return render(request, 'restaurants/detail.html', { 
    'restaurant': restaurant, 'reservation_form': reservation_form,
    'dishes': dishes_restaurant_doesnt_have  
  })

@login_required
def assoc_dish(request, restaurant_id, dish_id):
  # Note that you can pass a dish's id instead of the whole object
  Restaurant.objects.get(id=restaurant_id).dishes.add(dish_id)
  return redirect('detail', restaurant_id=restaurant_id)


#   print(request.POST['time'])
#   time = request.POST['time']
#   hours = int(time.slice(0, time.index(':')))
  
#   reservation_object = {
#     'csrfmiddlewaretoken': request.POST['csrfmiddlewaretoken'],
#     'date': date.fromisoformat(request.POST['date']), 
#     'time': datetime.strptime(format_time, '%H:%M'),
#     'seating': request.POST['seating']
#   }
#   print("This is ", reservation_object)
  
@login_required
def add_reservation(request, restaurant_id):
  form = ReservationForm(request.POST)
  try:
    if form.is_valid():
      print("form is valid")
      new_reservation = form.save(commit=False)
      new_reservation.restaurant_id = restaurant_id
      new_reservation.save()
    return redirect('detail', restaurant_id=restaurant_id)
  except:
    print("form not valid")

@login_required
def delete_reservation(request, restaurant_id, reservation_id):
    Reservation.objects.filter(id=reservation_id).delete()
    return redirect('detail', restaurant_id=restaurant_id)

class RestaurantCreate(LoginRequiredMixin, CreateView):
  model = Restaurant
  fields = '__all__'

  def form_valid(self, form):
    # Assign the logged in user (self.request.user)
    form.instance.user = self.request.user  # form.instance is the restaurant
    # Let the CreateView do its job as usual
    return super().form_valid(form)

class RestaurantUpdate(LoginRequiredMixin, UpdateView):
  model = Restaurant
  fields = ['cuisine', 'description', 'city','country','stars']

class RestaurantDelete(LoginRequiredMixin, DeleteView):
  model = Restaurant
  success_url = '/restaurants/'

class DishList(LoginRequiredMixin, ListView):
  model = Dish

class DishDetail(LoginRequiredMixin, DetailView):
  model = Dish

class DishCreate(LoginRequiredMixin, CreateView):
  model = Dish
  fields = '__all__'

class DishUpdate(LoginRequiredMixin, UpdateView):
  model = Dish
  fields = ['name', 'description']

class DishDelete(LoginRequiredMixin, DeleteView):
  model = Dish
  success_url = '/dishes/' 

restaurantcollector/main_app/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Restuarant Collector</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
    <h1>About the Restaurant Collector</h1>
    <hr />
    <p>The best place to view your favourite restuarants and dishes.</p>
    <footer>All Rights Reserved, &copy; 2021 Restaurant Collector</footer>
    {% endblock %}
</body>
</html>

restaurantcollector/main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Restaurant Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Restaurant Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'dishes_create' %}">Add a Dish</a></li>
            <li><a href="{% url 'dishes_index' %}">View All Dishes</a></li>
            <li><a href="{% url 'restaurants_create' %}">Add a Restaurant</a></li>
            <li><a href="{% url 'index' %}">View All My Restaurants</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
          {% else %}
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
  {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2021 Restaurant Collector &nbsp;</div>
  </footer>
</body>
</html>

restaurantcollector/main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

restaurantcollector/main_app/templates/main_app/dish_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Dish</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'dishes_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

restaurantcollector/main_app/templates/main_app/dish_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Dish Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ dish.name }}</span>
        <p>Description: {{ dish.description }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'dishes_update' dish.id %}">Edit</a>
        <a href="{% url 'dishes_delete' dish.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

restaurantcollector/main_app/templates/main_app/dish_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Dish</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

restaurantcollector/main_app/templates/main_app/dish_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Dish List</h1>

{% for dish in dish_list %}
  <a href="{% url 'dishes_detail' dish.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ dish.name }}</span>
            <p>Description: {{ dish.description }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

restaurantcollector/main_app/templates/main_app/restaurant_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Restaurant</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' restaurant.id %}">Cancel</a>
  </form>
{% endblock %}

restaurantcollector/main_app/templates/main_app/restaurant_form.html
{% extends 'base.html' %}

{% block content %}
    {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
    {% else %}
    <h1>Add Restaurant</h1>
    {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

restaurantcollector/main_app/templates/restaurants/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Restaurant Detail</h1>
<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ restaurant.name }}</span>
                <p>Cuisine: {{ restaurant.cuisine }}</p>
                <p>Description: {{ restaurant.description }}</p>
                {% if restaurant.stars > 2 %}
                <p>Rating: {{ restaurant.stars }} Stars</p>
                {% else %}
                <p>Rating: Would Not Recommend</p>
                {% endif %}
                <p>City: {{restaurant.city}}</p>
                <p>Country: {{restaurant.country}}</p>
            </div>
        <div class="card-action">
            <a href="{% url 'restaurants_update' restaurant.id %}">Edit</a>
            <a href="{% url 'restaurants_delete' restaurant.id %}">Delete</a>
        </div>
        </div>
    </div>
    
    <div class="col s6">
      
      <form action="{% url 'add_reservation' restaurant.id %}" method="post">
        {% csrf_token %}
        {{ reservation_form.as_p }}
        <input type="submit" id="reservation-btn" class="btn" value="Add Reservation">
      </form>

        <table class="striped">
          <thead>
            <tr><th>Date</th><th>Time</th><th>Seating</th></tr>
          </thead>
          <tbody>
            {% for reservation in restaurant.reservation_set.all %}
              <tr>
                <td>{{reservation.date}}</td>
                <td>{{reservation.time}}</td>
                <td>{{reservation.get_seating_display}}</td>
                <td>
                  <form method='POST' action="{% url 'delete_reservation' restaurant.id reservation.id %}">
                    {% csrf_token %}
                    <button type="submit" class='btn'>Delete</button>
                  </form>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
</div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ restaurant.name }}'s Dishes</h3>
    {% if restaurant.dishes.count %}
      {% for dish in restaurant.dishes.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              {{ dish.name }}  
            </span>
            {{ dish.description }}
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Dishes :(</h5>
    {% endif %}
  </div>
  <!-- Available dishes will come after this line -->
  <div class="col s6">
    <h3>Available Dishes</h3>
    {% if dishes.count %}
      {% for dish in dishes.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              {{ dish.name }}
            </span>
            {{ dish.description }}
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_dish' restaurant.id dish.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{restaurant.name}} Already Has All Dishes Available</h5>
    {% endif %}
  </div>
</div>

<script>
  var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  var selectEl = document.getElementById('id_seating');
  M.FormSelect.init(selectEl);

  var timeEl = document.getElementById('id_time');
  M.Timepicker.init(timeEl, {
    default: 'now',
    twelvehour: false, // change to 12 hour AM/PM clock from 24 hour
    donetext: 'OK',
    autoclose: false,
    
  });

  let reservationBtn = document.getElementById('reservation-btn');

  reservationBtn.addEventListener('click', function() {
    let time = timeEl.value;
    let hours = parseInt(time.slice(0, time.indexOf(':')));
    if (time.endsWith("AM")){
        if (hours === 12){
            hours = 0;
        }
    } else {
        if (hours < 12){
            hours += 12;
        }
    }
    let minutes = time.slice(time.indexOf(':'), time.indexOf(' '));
    let clock = `${hours}${minutes}`
    timeEl.value = clock;
})  

</script>

{% endblock %}

restaurantcollector/main_app/templates/restaurants/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Restaurant List</h1>

{% for restaurant in restaurants %}
  <div class="card">
  <a href="{% url 'detail' restaurant.id %}">
    <div class="card-content">
      <span class="card-title">{{ restaurant.name }}</span>
      <p>Cuisine: {{ restaurant.cuisine }}</p>
      <p>Description: {{ restaurant.description }}</p>
      {% if restaurant.stars > 2 %}
        <p>Rating: {{ restaurant.stars }} Stars</p>
      {% else %}
        <p>Rating: Would Not Recommend</p>
      {% endif %}
      <p>City: {{restaurant.city}}</p>
      <p>Country: {{restaurant.country}}</p>
    </div>
  </a>
  </div>
{% endfor %}

{% endblock %}